project:
  type: website
  output-dir: docs

website:
  title: "PSY Statistics Courses"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "PSY 371 — Intro Stats"
        href: psy371/index.qmd
      - text: "PSY 771 — ANOVA"
        href: psy771/index.qmd

format:
  html:
    theme: cosmo
    toc: true
    embed-resources: false

editor: visual
